.libPaths()
install.packages(c("optparse", "shazam", "alakazam", "tigger", "scoper", "BiocManager"), repos = "https://cloud.r-project.org")
BiocManager::install(c("edgeR"))

library(shazam)
library(alakazam)
library(tigger)
library(airr)
library(optparse)
library(edgeR)
