.libPaths()
install.packages(c("BiocManager"), repos = "https://cloud.r-project.org")
BiocManager::install(c("edgeR", "Biostrings", "GenomicAlignments", "IRanges"))
install.packages(c("shazam", "alakazam", "tigger", "scoper"))

library(shazam)
library(alakazam)
library(tigger)
library(airr)
library(optparse)
library(edgeR)
