.libPaths()
install.packages(c("BiocManager"), repos = "https://cloud.r-project.org")
BiocManager::install(c("edgeR"))
install.packages(c("alakazam", "tigger", "scoper"))

library(shazam)
library(alakazam)
library(tigger)
library(airr)
library(optparse)
library(edgeR)
