name: General
description: General comment box
body:
  - type: textarea
    id: description
    attributes:
      label: Description of the issue
      description: A clear and concise description of what the issue is.
