name: Code style checks

on: [pull_request]

jobs:
  black:
    name: Check black compliance.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install black
        run: python -m pip install black

      - name: Run black
        run: black --config pyproject.toml --check .

  docstring:
    name: Check docstring compliance.
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install interrogate
        run: python -m pip install interrogate

      - name: Run interrogate
        run: interrogate .
